### ISSUE TITLE
Inventory/JEI crash (ItemAir cannot be cast to ItemBlock)

### ISSUE THREAD

**Issue by kevsgrove** [davqvist/Exoria#185]
Crash occurs when opening my inventory while searching "craft" in JEI's textbox. Chisels & Bits's "positive print" item it seems is the problem.

Here are some lines from the crash log that are relevant. I don't want to upload it all to pastebin but I will if necessary.

-- Ingredient being rendered --
Details:
	Ingredient Mod: Chisels & Bits
	Ingredient Info: 1xitem.mod.chiselsandbits.positiveprint@0 chiselsandbits:positiveprint
Stacktrace:
	at mezz.jei.render.IngredientRenderer.createRenderIngredientException(IngredientRenderer.java:220)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:32)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:162)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:90)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:209)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:74)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2179_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)

**Comment by kevsgrove** [comment]
If anyone else is experiencing this, I've found that upon reloading the game, I've had to open my inventory and quickly clear JEI's textbox to prevent repeated crashes.

**Comment by davqvist** [comment]
Duplicate to https://github.com/davqvist/Exoria/issues/173
Disable C&B temporarily if on SP, it happens when in JEI certain items appear.

**Comment by kevsgrove** [comment]
Indeed is a duplicate, my apologies. I searched for the issue but I guess I just overlooked that report
