### ISSUE TITLE
Flexible Tools crashes server when breaking Rock from Immersive Craft

### ISSUE THREAD

**Issue by unlimitedsola** [davqvist/Exoria#277]
Step to reproduce:
1. Break Rock from Immersive Craft with Flexible Axpickvel from Flexible Tools

Note:
- Won't crash the game if in single-player
- Does crash the server if in multi-player

Crash report:
```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
        at net.minecraft.util.Util.runTask(SourceFile:539)
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.minecraft.util.Util.func_181617_a(SourceFile:539)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        ... 2 more
```

**Comment by KidsDontPlay** [comment]
no idea
I couldn't reproduce the problem
what upgrades have you installed in the tool?
Edit: do you use the latest version?

**Comment by unlimitedsola** [comment]
I'm using the latest version (of Exoria modpack) , the Axpickvel is fresh new doesn't have any upgrade

**Comment by unlimitedsola** [comment]
Closing as I haven't played for a long while and I want to clean up my pending list a bit.
